config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  get "home/about", to: 'homes#about', as: :homes_about
  get '/search', to: 'searches#search'
  get 'categories/index'

  resources :users, only: [:show, :create, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
      get :follows, on: :member
      get :followers, on: :member
  end

  resources :books, only: [:show, :edit, :create, :index, :destroy, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: :followed_id
  has_many :followed, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :follower, through: :passive_relationships, source: :followed
  attachment :profile_image

  validates :name, uniqueness: true,
            length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}

  def followed_by?(user)
    passive_relationships.where(followed_id: user.id).exists?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def follows
    user = User.find(params[:id])
    @users = user.followed
  end

  def followers
    user = User.find(params[:id])
    @users = user.follower
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render "users/edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg",size: "100x100" %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>follows</th>
      <td>
        <%= link_to follows_user_path(user) do %>
          <%= user.active_relationships.count %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th>followers</th>
      <td>
        <%= link_to followers_user_path(user) do %>
          <%= user.passive_relationships.count %>
        <% end %>
      </td>
    </tr>
    <tr>
      <% if user == current_user %>
        <th colspan="2">
          <%= link_to edit_user_path(current_user), class:"btn btn-default btn-block" do %> <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
          <% end %>
        </th>
      <% else %>
        <tr>
          <td style="border:none;">
            <% if user.followed_by?(current_user) %>
              <%= link_to "フォロー外す", user_relationships_path(user), method: :delete, class: "btn btn-primary" %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user), method: :post, class: "btn btn-success" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tr>
  </tbody>
</table>
<div class="row">
  <%= link_to (edit_user_path(user.id)), class:"btn btn-outline-secondary btn-block fas fa-user-cog" do %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <div id = "error_explanation">
        <% if @user.errors.any? %>
          <% if @user.errors.count == 1 %>
            <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
          <% else %>
            <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
          <% end %>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
      <%= form_with model:@user, local:true do |f| %>
        <div class="form-grop">
          <label>Name</label><br>
          <%= f.text_field :name, class:"form-control name" %><br>
        </div>
        <div class="form-grop">
          <label>Image</label><br>
          <%= f.attachment_field :profile_image, class:"form-control-file user_image" %><br>
        </div>
        <div class="form-grop">
          <label>Introduction</label><br>
          <%= f.text_area :introduction, class:"form-control introduction" %><br>
        </div>
        <div class="form-grop">
          <%= f.submit "Update User", class:"btn btn-secondary" %><br>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<table class="table table-sm">
  <h2>Follower Users</h2>
  <thead>
    <th>image</th>
    <th>name</th>
    <th colspan="4"></th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg"%></td>
      <td><%= user.name %></td>
      <td>フォロー数：<%= user.active_relationships.count %></td>
      <td>フォロワー数：<%= user.passive_relationships.count %></td>
      <td><%= link_to "Show", "/users/#{user.id}" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/follows.html.erb
<table class="table table-sm">
  <h2>Follow Users</h2>
  <thead>
    <th>image</th>
    <th>name</th>
    <th colspan="4"></th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg"%></td>
      <td><%= user.name %></td>
      <td>フォロー数：<%= user.active_relationships.count %></td>
      <td>フォロワー数：<%= user.passive_relationships.count %></td>
      <td><%= link_to "Show", "/users/#{user.id}" %></td>
    </tr>
    <% end %>
  </tbody>
</table> 

app/views/users/index.html.erb
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= render 'users/user', user: @user %>
        <h2 class="mt-3">New book</h2>
        <%= render 'books/new', book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th colspan="3"></th>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></td>
                <td><%= user.name %></td>
                <td>フォロー数：<%= user.active_relationships.count %></td>
                <td>フォロワー数：<%= user.passive_relationships.count %></td>
                <td>
                  <% if current_user != user %>
                    <% if user.followed_by?(current_user) %>
                      <%= link_to "フォロー外す", user_relationships_path(user), method: :delete %>
                    <% else %>
                      <%= link_to "フォローする", user_relationships_path(user), method: :post %>
                    <% end %>
                  <% end %>
                </td>
                <td><%= link_to "Show", user_path(user.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= render 'users/user', user: @user %>
        <h2 class="mt-3">New book</h2>
        <%= render 'books/new', book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <%= render 'books/index', books: @books %>
      </div>
    </div>
  </div>