config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  get "home/about", to: 'homes#about', as: :homes_about
  get '/search', to: 'searches#search'
  get 'categories/index'

  resources :users, only: [:show, :create, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
      get :follows, on: :member
      get :followers, on: :member
  end

  resources :books, only: [:show, :edit, :create, :index, :destroy, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  scope :latest, -> {order(created_at: :desc)}
  scope :evaluation, -> {order(rate: :desc)}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  validates :rate, presence: true
  validates :category, presence: true

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    if params[:sort_create]
      @books = Book.latest
    elsif params[:sort_rate]
      @books = Book.evaluation
    else
      @books = Book.all
    end
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @newbook = Book.new
    @book_comment = BookComment.new
    @user = User.find(@book.user_id)
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @user = current_user
      @books = Book.all.order(updated_at: :asc)
      render "books/index"
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      @books = Book.all
      render "books/edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
      flash[:notice]="Book was successfully destroyed."
      redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :rate, :category)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_index.html.erb
  <table class="table table-hover table-inverse">
    <thead>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Category</th>
      <th></th>
      <th></th>
      <th></th>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <% user = User.find(book.user_id) %>
        <tr>
          <td>
            <%= link_to user_path(user.id) do %>
              <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
              <%= book.title %>
            <% end %>
          </td>
          <td><%= book.body %></td>
          <td>
            <%= link_to categories_index_path(search: book.category) do %>
              <%= book.category %>
            <% end %>
          </td>
          <td id="favorite_buttons_<%= book.id %>">
            <%= render 'favorites/favorite', book: book %>
          </td>
          <td>コメント数：<%= book.book_comments.count %></td>
          <td class="relative-book-rate">
            <span id="star-rate-<%= book.id %>"></span>
            <script>
            　$('#star-rate-<%= book.id %>').empty();
              $('#star-rate-<%= book.id %>').raty({
                size: 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= book.rate %>
              });
            </script>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/books/_new.html.erb
　<%= form_with model:book, local:true do |f| %>
    <div class="form-group">
      <label for="book_title">Title</label>
      <%= f.text_field :title, class:"form-control book_title"%>
    </div>
    <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body, class:"form-control book_body"%>
    </div>
    <div class="form-group">
      <label for="book_category">Category</label>
      <%= f.text_field :category, class:"form-control book_category" %>
    </div>
    <span>Rate</span>
    <div class="field" id="star" style="display: inline-block;">
      <%= f.label :rate %>
      <%= f.hidden_field :rate, id: :review_star %>
    </div>
  　<script>
    　$('#star<%= book.id %>').empty();
      $('#star').raty({
        size     : 36,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        scoreName: 'book[rate]',
        half: true,
      });
  　</script>
    <div class="form-group mt-3">
      <%= f.submit 'Create Book', class:"btn btn-success" %>
    </div>
  <% end %>

app/views/books/edit.html.erb
  <div class="container">
    <div class="row">
      <div class="col-sm-2 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <div id = "error_explanation">
          <% if @book.errors.any? %>
            <% if @book.errors.count == 1 %>
              <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
            <% else %>
              <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
            <% end %>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
        <%= form_with model:@book, local:true do |f| %>
          <div class="form-group">
            <label for="inputTitle">Title</label><br>
            <%= f.text_field :title, class:"form-control book_title"%><br>
          </div>
          <div class="form-group">
            <label for="inputbody">Opinion</label><br>
            <%= f.text_area :body, class:"form-control book_body" %><br>
          </div>
          <div class="form-group">
            <label for="book_category">Category</label>
            <%= f.text_field :category, class:"form-control book_category" %>
          </div>
          <div class="relative-book-rate">
            <span id="star-rate-<%= @book.id %>"></span>
            <script>
            　$('#star-rate-<%= @book.id %>').empty();
              $('#star-rate-<%= @book.id %>').raty({
                size: 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= @book.rate %>
              });
            </script>
          </div>
          <div class="form-group mt-4">
            <%= f.submit "Update Book", class:"btn btn-success" %><br>
          </div>
        <% end %>
        <%= link_to "Show", book_path(@book.id) %>
        |
        <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>

app/views/books/index.html.erb
  <div class="container px-5 px-sm-0">
    <div id="error_explanation">
      <% if @book.errors.any? %>
        <h3>
          <%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= render 'users/user', user: @user %>
        <h2 class="mt-3">New book</h2>
        <%= render 'books/new', book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <%= link_to '新しい順', books_path(sort_create: "true") %>
        |
        <%= link_to '評価の高い順', books_path(sort_rate: "true") %>
        <%= render 'books/index', books: @books %>
      </div>
    </div>
  </div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/user', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/new', book: @newbook %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag(@user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40") %><br>
              　<%= @user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to @book.title, book_path(@book) %>
            </td>
            <td><%= @book.body %></td>
            <td><%= @book.category %></td>
            <td id="favorite_buttons_<%= @book.id %>" style="padding-left: 0;">
              <%= render 'favorites/favorite', book: @book %>
            </td>
            <td>コメント数：<%= @book.book_comments.count %></td>
            <td class="relative-book-rate">
              <span id="star-rate-<%= @book.id %>"></span>
              <script>
              　$('#star-rate-<%= @book.id %>').empty();
                $('#star-rate-<%= @book.id %>').raty({
                  size: 36,
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  half: true,
                  readOnly: true,
                  score: <%= @book.rate %>
                });
              </script>
            </td>
            <% if @book.user_id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class:"btn btn-sm btn-danger" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <div id="comments_area">
        <%= render 'book_comments/comment', book: @book %>
      </div>
      <%= render 'book_comments/form', book: @book, book_comment: @book_comment %>
    </div>
  </div>
</div>