config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  get "home/about", to: 'homes#about', as: :homes_about
  get '/search', to: 'searches#search'
  get 'categories/index'

  resources :users, only: [:show, :create, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
      get :follows, on: :member
      get :followers, on: :member
  end

  resources :books, only: [:show, :edit, :create, :index, :destroy, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  scope :latest, -> {order(created_at: :desc)}
  scope :evaluation, -> {order(rate: :desc)}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  validates :rate, presence: true
  validates :category, presence: true

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

belongs_to :user
belongs_to :book

validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord

   belongs_to :follower, class_name: "User"
   belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: :followed_id
  has_many :followed, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :follower, through: :passive_relationships, source: :followed
  attachment :profile_image

  validates :name, uniqueness: true,
            length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}

  def followed_by?(user)
    passive_relationships.where(followed_id: user.id).exists?
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    if params[:sort_create]
      @books = Book.latest
    elsif params[:sort_rate]
      @books = Book.evaluation
    else
      @books = Book.all
    end
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @newbook = Book.new
    @book_comment = BookComment.new
    @user = User.find(@book.user_id)
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @user = current_user
      @books = Book.all.order(updated_at: :asc)
      render "books/index"
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      @books = Book.all
      render "books/edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
      flash[:notice]="Book was successfully destroyed."
      redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :rate, :category)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @model = params["model"]
    @content = params["content"]
    @method = params["method"]
    @records = search_for(@model, @content, @method)
  end

  private

  def search_for(model, content, method)
    if model == 'user'
      if method == 'perfect'
        User.where(name: content)
      elsif method == 'for_ward'
        User.where('name LIKE ?', content+'%')
      elsif method == 'back_ward'
        User.where('name LIKE ?', '%'+content)
      elsif method == 'partial'
        User.where('name LIKE ?', '%'+content+'%')
      end
    elsif model == 'book'
      if method == 'perfect'
        Book.where(title: content)
      elsif method == 'for_ward'
        Book.where('title LIKE ?', content+'%')
      elsif method == 'back_ward'
        Book.where('title LIKE ?', '%'+content)
      elsif method == 'partial'
        Book.where('title LIKE ?', '%'+content+'%')
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def follows
    user = User.find(params[:id])
    @users = user.followed
  end

  def followers
    user = User.find(params[:id])
    @users = user.follower
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render "users/edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/a98d9d5887.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to root_path, class:"navbar-brand" do %>
          <span>Bookers</span>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-expanded="false" aria-controls="navbarNavDropdown" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <% if user_signed_in? %>
              <ul class="navbar-nav ml-auto">
                <li><%= link_to ' Home', user_path(current_user.id), class:"fas fa-home nav-link text-light font-weight-bold"%></li>
                <li><%= link_to " Users", users_path, class:"fas fa-users nav-link text-light font-weight-bold" %></li>
                <li><%= link_to ' Books', books_path, class:"fas fa-book-open nav-link text-light font-weight-bold" %></li>
                <li><%= link_to ' logout', destroy_user_session_path, method: :delete,class: 'fas fa-sign-out-alt nav-link text-light' %></li>
                <li>
                  <%= form_tag({controller:"categories", action:"index"}, method: :get) do %>
                    <%= text_field_tag :search %>
                    <%= submit_tag '検索', class:"btn btn-primary" %>
                  <% end %>
                 </li>
              </ul>
            <% else %>
              <ul class="navbar-nav ml-auto">
                <li><%= link_to ' Home', root_path, class:"fas fa-home nav-link text-light font-weight-bold"%></li>
                <li><%= link_to " About", homes_about_path, class:"fas fa-link nav-link text-light font-weight-bold" %></li>
                <li><%= link_to " sign up", new_user_registration_path, class:"fas fa-user-plus nav-link text-light font-weight-bold" %></li>
                <li><%= link_to " login", new_user_session_path, class:"fas fa-sign-in-alt nav-link text-light font-weight-bold" %></li>
              </ul>
            <% end %>
          </div>
        </div>
      </nav>
      <%= render 'searches/form' %>
    </header>

    <main>
      <% if flash[:notice] %>
        <% flash.each do |key, msg| %>
          <p id="notice">
            <%= msg %>
          </p>
        <% end %>
      <% else %>
        <p id="notice"></p>
      <% end %>
      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>